#!/usr/bin/env sh

limelight -m config width 3
limelight -m config radius 12
limelight -m config placement exterior
# limelight -m config active_color 0xFF5B2581
limelight -m config active_color 0xFF7F00FF
# limelight -m config active_color 0xFFBF40BF
# limelight -m config active_color 0xFF800080
limelight -m config normal_color 0x00FFFFFF

echo "limelight configuration loaded.."
