#!/usr/bin/env sh
#YABAI STUFF

# bsp or float (default: bsp)
yabai -m config layout bsp

# float system preferences. Most of these just diable Yabai form resizing them.
yabai -m rule --add app="^System Settings$" layer=above manage=off
yabai -m rule --add app="^Disk Utility$" layer=above manage=off
yabai -m rule --add app="^System Information$" layer=above manage=off
yabai -m rule --add app="^Activity Monitor$" layer=above manage=off
yabai -m rule --add app="zoom" manage=off
yabai -m rule --add app="^Wally" manage=off
yabai -m rule --add app="Outlook" title="Reminder" layer=above manage=off
yabai -m rule --add app="OneDrive" layer=above manage=off
#yabai -m rule --add app="^Spotify$" manage=off


## Some random global settings
#yabai -m config focus_follows_mouse          autoraise
#yabai -m config mouse_follows_focus          on
# New window spawns to the right if vertical split, or bottom if horizontal split
yabai -m config window_placement second_child
yabai -m config window_topmost off
#yabai -m config window_shadow float
yabai -m config window_opacity off
#yabai -m config window_opacity_duration 0.00
#yabai -m config active_window_opacity 1.0
#yabai -m config normal_window_opacity        0.97
#yabai -m config window_border                on | off

## WITH SIP ENABLED (Installed Limelight seperately, Don't need this)
# yabai -m config window_border off

## WTIH SIP DISABLED (Limelight build into Yabai, enable it here)
yabai -m config window_border on
yabai -m config window_border_width 3
yabai -m config window_border_radius 12
# yabai -m config active_window_border_color 0xFF7F00FF # nicer colour, but doesn't have contrast with Monterey background
yabai -m config active_window_border_color 0xFFBA86F6
# yabai -m config normal_window_border_color 0x00FFFFFF
yabai -m config normal_window_border_color 0xFF333333
# yabai -m config insert_feedback_color      0xffd75f5f
yabai -m config insert_feedback_color      0xffFF0000

## an attempt to fix blurred windows, eg when scoot was active
# see https://github.com/koekeishiya/yabai/issues/1471
yabai -m config window_border_blur off

## some other settings
yabai -m config auto_balance off
yabai -m config split_ratio 0.50

# general space settings
#yabai -m config focused_border_skip_floating  1
#yabai -m config --space 3 layout             float

## Change how yabai looks
yabai -m config top_padding 5
yabai -m config bottom_padding 5
yabai -m config left_padding 10
yabai -m config right_padding 10
yabai -m config window_gap 10

#Limelight addon (Kill it and start it each time Yabai starts)
# killall limelight &>/dev/null
# limelight &>/dev/null &

## An attempt to fix this: https://github.com/koekeishiya/yabai/issues/68
# Refresh yabai if a tab in finder or terminal is created or moved to new window
yabai -m signal --add event=window_created app="^Terminal$|^Finder$" \
    action="yabai -m space --focus next && sleep 0.01 && yabai -m space --focus prev"

yabai -m signal --add event=window_destroyed app="^Terminal$|^Finder$" \
    action="yabai -m space --focus next && sleep 0.01 && yabai -m space --focus recent"

yabai -m signal --add event=window_moved app="^Terminal$|^Finder$" \
    action="yabai -m space --focus next && sleep 0.01 && yabai -m space --focus recent"

yabai -m signal --add event=window_resized app="^Terminal$|^Finder$" \
    action="yabai -m space --focus next && sleep 0.01 && yabai -m space --focus recent"

echo "yabai configuration loaded.."

#END
