#!/usr/bin/env sh
#YABAI STUFF

# bsp or float (default: bsp)
yabai -m config layout bsp

# float system preferences. Most of these just disable Yabai form resizing them.
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Disk Utility$" layer=above manage=off
yabai -m rule --add app="^System Information$" layer=above manage=off
yabai -m rule --add app="^Activity Monitor$" layer=above manage=off
yabai -m rule --add app="Outlook" title="Reminder" layer=above manage=off
yabai -m rule --add app="OneDrive" layer=above manage=off
yabai -m rule --add app="OneDrive" title="^Version History" layer=above manage=off
#yabai -m rule --add app="^Spotify$" manage=off


## Some random global settings
#yabai -m config focus_follows_mouse          autoraise
#yabai -m config mouse_follows_focus          on
# New window spawns to the right if vertical split, or bottom if horizontal split
yabai -m config window_placement second_child
yabai -m config window_topmost off
#yabai -m config window_shadow float
yabai -m config window_opacity off
#yabai -m config window_opacity_duration 0.00
#yabai -m config active_window_opacity 1.0
#yabai -m config normal_window_opacity        0.97

borders active_color=0xFFBA86F6 inactive_color=0xff494d64 width=10.0 &

## some other settings
yabai -m config auto_balance on
yabai -m config split_ratio 0.50

# general space settings
#yabai -m config focused_border_skip_floating  1
#yabai -m config --space 3 layout             float

## Change how yabai looks
yabai -m config top_padding    15
yabai -m config bottom_padding 15
yabai -m config left_padding   15
yabai -m config right_padding  15
yabai -m config window_gap     15

## An attempt to fix this: https://github.com/koekeishiya/yabai/issues/68
# Refresh yabai if a tab in finder or terminal is created or moved to new window
yabai -m signal --add event=window_created app="^Terminal$|^Finder$" \
    action="yabai -m space --focus next && sleep 0.01 && yabai -m space --focus prev"

yabai -m signal --add event=window_destroyed app="^Terminal$|^Finder$" \
    action="yabai -m space --focus next && sleep 0.01 && yabai -m space --focus recent"

yabai -m signal --add event=window_moved app="^Terminal$|^Finder$" \
    action="yabai -m space --focus next && sleep 0.01 && yabai -m space --focus recent"

yabai -m signal --add event=window_resized app="^Terminal$|^Finder$" \
    action="yabai -m space --focus next && sleep 0.01 && yabai -m space --focus recent"

yabai -m signal --add app='^Ghostty$' event=window_created action='yabai -m space --layout bsp'
yabai -m signal --add app='^Ghostty$' event=window_destroyed action='yabai -m space --layout bsp'

echo "yabai configuration loaded.."

#END
